# Generated by Django 5.2.5 on 2025-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=50)),
                ('event_date', models.DateField()),
                ('artist_name', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='gigs', to='stats.profile')),
            ],
            options={
                'verbose_name': 'Gig',
                'verbose_name_plural': 'Gigs',
                'ordering': ['-event_date'],
                'unique_together': {('event_date', 'artist_name', 'venue', 'city', 'country')},
            },
        ),
    ]
